import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavMenuHome from "@/src/component/home/NavMenuHome";
import FooterLayout from "@/src/component/home/FooterLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased`}
		>
       <NavMenuHome />
			<div className="h-screen w-screen">
				<div className="w-full">
					{children}
          <FooterLayout />
				</div>
			</div>
		</body>
    </html>
  );
}
